config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'listings#index'


  get '/admin/users', to: 'admin#users'
  get '/admin/listings', to: 'admin#listings'
  get '/admin/agents', to: 'admin#agents'
  get '/admin/analytics', to: 'admin#analytics'
  get '/agentregistration', to: 'agents#new'
  get 'search', to: 'listings#search_results'
  get 'account', to: 'users#show'
  get 'userlistings', to: "users#user_listings"
  get 'messages', to: "users#user_messages"
  get 'interested/:id', to:"listings#interest_indication_form"

  post '/images/upload', to: 'images#upload'
  post "/interest_indications", to: "listings#create_interest_indications"
  post '/images/remove_image', to: 'images#remove_image'

  patch '/images/remove_image', to: 'images#remove_image'
  patch '/images/upload', to: 'images#upload'

  resources :listings
  resources :statics
  resources :admin
  resources :agents
  resources :users

end

app/models/agent.rb
class Agent < ApplicationRecord
  belongs_to :user

  has_one :image_proxy, as: :proxy_owner, dependent: :destroy
  has_many :listings
  accepts_nested_attributes_for :image_proxy, allow_destroy: true

  def get_interest_indications
    interest_inds = []
    self.listings.each do |listing|
      listing.interest_indications.each do |ii|
        interest_inds << ii
      end
    end
    return interest_inds
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  def print_errors
    if self.errors.any? 
      puts "Errors: "
      self.errors.full_messages.each do |message| 
        puts message 
      end
    end
  end
end

app/models/guest.rb
class Guest < ApplicationRecord
  has_one :interest_indication
end

app/models/house_detail.rb
class HouseDetail < ApplicationRecord
  belongs_to :listing
end

app/models/image.rb
require 'aws-sdk-s3'

class Image < ApplicationRecord
  # Mount Carrier Wave image uploader
  mount_uploader :image, ImageUploader

  def upload_to_s3 path
    s3 = Aws::S3::Resource.new(
      region: ENV.fetch("AWS_REGION")
    )
    bucket = ENV.fetch("AWS_BUCKET_NAME")
    name = File.basename(file)
    obj = s3.bucket(bucket).object(name)
    obj.upload_file(file)
  end
end

app/models/image_proxy.rb
class ImageProxy < ApplicationRecord
  belongs_to :proxy_owner, polymorphic: true, optional: true
  has_one :image


  # This is a hack. Please come up with a more standard way if possible.
  # def self.store(proxy_owner, proxy_attrbutes)
  #   images_attributes.values.each do |value|
  #     if value.has_key? :image_url
  #       # Remove the :_destroy key. 
  #       value.delete :_destroy
  #       if image_owner && value[:image]
  #         new_image = Image.new
  #         new_image.image_owner = image_owner
  #         new_image.image = value[:image]
  #         # If it is not possible to save this image with the given records,
  #         # print the error and return false.
  #         if !new_image.save
  #           new_image.print_errors
  #           return false
  #         end
  #       else
  #         puts "Invalid params"
  #         return false
  #       end
  #     end
  #   end
  #   return true
  # end

  def upload_and_clean
    self.image.upload_and_clean
  end

end

app/models/interest_indication.rb
class InterestIndication < ApplicationRecord
  belongs_to :listing
  belongs_to :guest
end

app/models/listing.rb
class Listing < ApplicationRecord
  has_one :house_detail
  has_one :price
  has_one :location


  has_many :image_proxies, as: :proxy_owner, dependent: :destroy
  has_many :interest_indications

  belongs_to :agent
  
  accepts_nested_attributes_for :image_proxies, allow_destroy: true
  accepts_nested_attributes_for :location, allow_destroy: true
  accepts_nested_attributes_for :price, allow_destroy: true
  accepts_nested_attributes_for :house_detail, allow_destroy: true


  def self.search_listings(query)
      search_query = {}
      if (query[:listing_for])
        search_query[:listing_for] = query[:listing_for]
      end

      if (query[:city])
        search_query[:locations] ||= {}
        search_query[:locations][:city] = query[:city]
      end

      if (query[:neighborhood])
        search_query[:locations] ||= {}
        search_query[:locations][:neighborhood] = query[:neighborhood]
      end

      # house_details: {property_type: "*"}}
      return Listing.joins(:location, :house_detail).where(search_query)


  end

  def is_owned_by_user(user)
    return user.agent && agent == user.agent
  end

end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :listing
end

app/models/price.rb
class Price < ApplicationRecord
  belongs_to :listing
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :agent


  def promote_to_agent
    self.update!({role: "agent"})
  end


  def is_agent
    return self.role == "agent" || self.role == "admin"
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout "admin_layout"
  def index
  end 

  def users
    @users = User.all
  end

  def listings
    @listings = Listing.all
  end

  def agents
  end

  def analytics
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :user_signed_in
  before_action :user_is_agent, only: [:user_listings]
  def show
  end

  def user_listings
    @listings = current_user.agent.listings
  end

  def user_messages
    @listings = current_user.agent.listings
  end

  def log_out
    redirect_to destroy_user_session_path
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/agents_helper.rb
module AgentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/_admin_side_nav.html.erb
 <ul class="ad-nav-container">
  <li class="ad-nav-link"><a href="/admin/users"> Users </a></li>        
  <li class="ad-nav-link"><a href="/admin/listings"> Listings </a></li>
  <li class="ad-nav-link"><a href="/admin/agents"> Agents</a></li>
  <li class="ad-nav-link"><a href=""> Analytics </a></li>
</ul>

app/views/admin/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-inverse sch-navbar-bg">
  <div class = "container">
    <a class="navbar-brand rs-navbar-brand" href=<%= root_url %>><span class="rs-brand-light">Admin</span></a>
    <ul class="nav justify-content-center">
      <% if user_signed_in? %> 
        <% if current_user %>
          <li class="nav-item">
            <span class="nav-link"><%= current_user.email%></span>
          </li>
        <% end %>
        <% end %>
    </ul>
   </div>
</nav>

app/views/admin/agents.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3">
      <%= render(partial: "admin_side_nav")%>
    </div>
     <div class="col-md-9">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">First</th>
            <th scope="col">Last</th>
            <th scope="col">Handle</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <th scope="row">1</th>
            <td>Mark</td>
            <td>Otto</td>
            <td>@mdo</td>
          </tr>
          <tr>
            <th scope="row">2</th>
            <td>Jacob</td>
            <td>Thornton</td>
            <td>@fat</td>
          </tr>
          <tr>
            <th scope="row">3</th>
            <td>Larry</td>
            <td>the Bird</td>
            <td>@twitter</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/index.html.erb
<!--main content section-->
<section class="mt-4 mb-5">
  <div class="container">
    <div class="row">
      <div class="col-md-3">
        <div class="row mb-3">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <strong><p>Menu</p></strong>
                        <ul class="list-unstyled">
                           <a href="#"> <li>Digital Accuracy</li></a>
                           <a href="#"> <li>Digital Accuracy</li></a>
                           <a href="#"> <li>Digital Accuracy</li></a>
                           <a href="#"> <li>Digital Accuracy</li></a>
                           <a href="#"> <li>Digital Accuracy</li></a>
                           <a href="#"> <li>Digital Accuracy</li></a>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
      </div>
      <div class="col-md-9">
        <div class="row mb-3">
            <div class="col-md-12">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-3">
                               <img class="rs-search-result-img" src="https://s3.envato.com/files/248072868/Screenshot/01_preview.jpg">
                            </div>
                            <div class="col-md-7">
                                <h5>Msexchange contributes senior UX Designer</h5>
                                <small>Jopitor Inc., India</small>
                                <p><small>11907 Dyuuleves Incorpotatestion, South west, Newzealer</small></p>
                            </div>
                            <div class="col-md-2">
                                <button type="button" class="btn btn-outline bg-orange">Get Quotes</button>
                                <small>Published on Nov 27, 2017</small>
                            </div>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/admin/listings.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3">
      <%= render(partial: "admin_side_nav")%>
    </div>
     <div class="col-md-9">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Description</th>
            <th scope="col">City</th>
            <th scope="col">Area</th>
            <th scope="col">Price</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        <tbody>
          <% if @listings %>
          <% @listings.each do |listing|%>
          <tr>
            <th scope="row"><%= listing.id %></th>
            <td scope="row"><%= link_to(listing.title, listing_path(listing) )%></td>
            <td scope="row"><%= listing.location.city %></td>
            <td scope="row"><%= listing.location.neighborhood %></td>
            <td scope="row"><%= listing.price.amount %></td>
            <td scope="row"><%= link_to("Edit", edit_listing_path(listing)) %></td>
            <td scope="row"><%= link_to("Delete", edit_listing_path(listing)) %></td>
          </tr>
          <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/users.html.erb
<div class="container mt-4">
  <div class="row">
    <div class="col-md-3">
      <%= render(partial: "admin_side_nav")%>
    </div>
     <div class="col-md-9">
      <table class="table table-striped">
        <thead>
          <tr>
            <th scope="col">#</th>
            <th scope="col">Email</th>
            <th scope="col">Created At</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>
          </tr>
        </thead>
        
        <tbody>
          <% if @users %>
         <% @users.each do |user| %>

          <tr>
            <th scope="row">1</th>
            <td><%= user.email %></td>
            <td><%= user.created_at %></td>
            <td><%= link_to("Edit", edit_user_registration_path(user)) %></td>
            <td>Delete</td>
          </tr>
          <% end %>
          <% end %>
    
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rstate</title>
    <%= csrf_meta_tags %>  
  
    <%= stylesheet_link_tag('https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload')%>
    <%= stylesheet_link_tag('admin', media: 'all', 'data-turbolinks-track': 'reload')%>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
    <%=render(partial: "admin/nav") %>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rstate</title>
    <%= csrf_meta_tags %>  
    <%= stylesheet_link_tag('https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css', media: 'all', 'data-turbolinks-track': 'reload')%>
    <%= stylesheet_link_tag('application', media: 'all', 'data-turbolinks-track': 'reload')%>
    <%= stylesheet_link_tag("https://fonts.googleapis.com/css?family=IM+Fell+DW+Pica", media: 'all', 'data-turbolinks-track': 'reload')%>
    <%= stylesheet_link_tag("https://use.fontawesome.com/releases/v5.0.10/css/all.css", media: 'all', 'data-turbolinks-track': 'reload')%>
    <%= javascript_include_tag('application', 'data-turbolinks-track': 'reload')%>
    <%= javascript_include_tag('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js')%>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

  </head>

  <body>
    <%=render(partial: "partials/nav") %>
    <%= yield %>
  </body>
</html>

app/views/partials/_brand_logo.html.erb
<a class="navbar-brand rs-navbar-brand" href=<%= root_url %>><span class="rs-brand-light">Some name</span><span class="rs-brand-bold"> Here</span></a>

app/views/partials/_footer.html.erb
<hr>
<footer>
  <div style="min-height: 60px;" class="footer mt-4" id="footer-sub">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <%= render(partial: "partials/brand_logo")%>
          <p>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
          </p>
          
        </div>

       

      <div class="col-md-3">
        <h5>  </h5>
        <ul>

          <li><a href=""><i class="fas fa-phone"> </i> 0913123456</a></li>
         
        </ul>
      </div>

       <div class="col-md-3">
          <h5></h5>
          <ul>
           <li><a href=""><i class="fas fa-envelope"></i> info@somesite.com</a></li>  
                  
          </ul>
        </div> 
     
      </div>         
    </div>
  </div>

</footer>

app/views/partials/_nav.html.erb
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <div class="container"> 
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= render(partial: "partials/brand_logo") %>
    <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
      <ul class="navbar-nav ml-auto mt-2  my-2 my-lg-0">
        <% if user_signed_in? %>
          <% if (current_user.role == "admin" || current_user.role == "agent") %>
            <li class="nav-item">
              <a class="nav-link add-a-listing" href="/listings/new">Add A listing</a>
            </li>
          <% end %>
          <% if (current_user.role == "admin") %>
            <li class="nav-item">
              <a class="nav-link admin-link" href="/admin"><sapn><i class="fas fa-lock"> </i> admin</span></a>
            </li>
          <% end %>
        <li class="nav-item">
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <i class="fas fa-user-circle"></i> <%= current_user.email.split("@")[0] %>
            </a>
            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <%= link_to("My Account", "/account", class: "dropdown-item") %>
              <div class="dropdown-divider"></div>
              <%= link_to("Log Out", destroy_user_session_path, :method => :delete, class: "dropdown-item") %>
            </div>
          </li>
          
        </li>
        <% else %>

          <li class="nav-item">
            <%= link_to("Log In", new_user_session_path, class: "nav-link") %>
          </li>
          <li class="nav-item">
            <%= link_to("Sign Up", new_user_registration_path, class: "nav-link") %>
          </li>

        <% end %>

      </ul>
    </div>
  </div>
</nav>

app/views/partials/_not_found.html.erb
<div class="row">
  <div class="col-md-2">    
  </div>
  <div class="col-md-8">
    
    <h1> ይቅርታ! </h1>
    <hr>
    <h3> The <%= locals[:resource] %> you're looking for is not Found.
  </div>
  <div class="col-md-2">    
  </div>
</div>
<h1> 

app/views/partials/_wallpaper_overlay.html.erb
<div class="row">
  <div class="col-md-8">
    <div class="container">
      <div class="row rs-overlay">
        <div class="col-md-12">
          <div class="row rs-overlay-option"> Looking To : </div>
          <div class="row rs-overlay-option">
            <div class="btn-group" role="group" aria-label="Basic example">
              <button type="button" class="rs-overlay-btn btn active">Purchase</button>
              <button type="button" class="rs-overlay-btn btn">Rent</button>
            </div>            
          </div>
          <div class="row mt-4">
            <div class="btn-group" role="group" aria-label="Basic example">
              <div class="rs-overlay-option">
                Property Type :
                <select class="rs-overlay-select custom-select">
                  <option> A House</option>
                  <option> An Appartment</option>
                </select>     
              </div>

              <div class="rs-overlay-option">
                City : 
                <select class="rs-overlay-select custom-select">
                <option> Addis Ababa</option>
                <option> Adama </option>
                <option> Bahirdar</option>
                <option> Dire Dawa</option>
                <option> Mekele</option>
                <option> Gonder</option>
                <option> Hawassa</option>
              </select>
              </div>

              <div class="rs-overlay-option">
                Area : 
                <select class="rs-overlay-select custom-select">
                  <option> Bole </option>
                  <option> Adama </option>
                  <option> Bahirdar</option>
                  <option> Dire Dawa</option>
                  <option> Mekele</option>
                  <option> Gonder</option>
                  <option> Hawassa</option>
                </select>  
              </div>    
            </div>            
          </div>
          <div class="row mt-4">
           <button class="btn rs-btn-default">Search</button>     
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="col-md-4">

  </div>
</div>